# Generated by Django 5.2.6 on 2026-01-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('token', models.CharField(max_length=256)),
                ('extra', models.JSONField(default=dict)),
                ('by', models.SmallIntegerField(choices=[(1, 'login'), (2, 'regis')], default=1)),
            ],
        ),
    ]
